Connectivity:
  name: การสื่อสาร
Development:
  name: การพัฒนา
Graphics:
  name: กราฟิก
Internet:
  name: อินเทอร์เน็ต
Multimedia:
  name: สื่อผสม
Navigation:
  name: การนำทาง
Phone & SMS:
  name: โทรศัพท์และ SMS
Reading:
  name: การอ่าน
Science & Education:
  name: วิทยาศาสตร์และการศึกษา
Security:
  name: ความมั่นคง
Sports & Health:
  name: กีฬาและสุขภาพ
System:
  name: เครื่องมือระบบ
Theming:
  name: ธีมต่างๆ
Writing:
  name: การเขียน
