Connectivity:
  name: Conectividad
Development:
  name: Desarrollo
  description: Codificación, programación, IDE, terminal y herramientas para desarrolladores
Graphics:
  name: Gráficos
  description: Herramientas de edición de imágenes, manipulación fotográfica y diseño visual
Internet:
  name: Internet
Multimedia:
  name: Multimedia
Navigation:
  name: Navegación
  description: Mapas, GPS, direcciones de cambio y aplicaciones de planificación de rutas
Phone & SMS:
  name: Llamadas de teléfono y SMS
  description: Marcadores, gestores de llamadas y utilidades de mensajería de texto
Reading:
  name: Lectura
  description: Artículos, contenidos de larga duración, aplicaciones de lectura y lectura web
Science & Education:
  name: Ciencia y Educación
  description: Aprender, estudiar, hacer referencia y aplicaciones educativas
Security:
  name: Seguridad
Sports & Health:
  name: Deportes y Salud
  description: Seguimiento de la actividad física, bienestar, puntuaciones deportivas y monitorización de la salud
System:
  name: Sistema
Theming:
  name: Colores e interfaz
  description: Personaliza el aspecto de tu dispositivo con temas, fuentes y estilos UI
Writing:
  name: Escritura
Email:
  name: Correo-e
  description: Clientes de correo-e para enviar, recibir y gestionar mensajes de correo-e
VPN & Proxy:
  name: Redes privadas (VPN) y proxies
  description: Cifrar tráfico, evadir restricciones (circunvención) y anonimizar tu conexión
DNS & Hosts:
  name: DNS y Hospedajes
  description: Configurar resoluciones DNS, bloqueo de anuncios, archivo hosts y enrutamiento de dominios
File Transfer:
  name: Transferencia de archivo
  description: Comparta y transfiera archivos a través de FTP, LAN, Bluetooth o peer-to-peer (p2p)
Messaging:
  name: Mensajería
  description: Aplicaciones de mensajería instantánea, chat y comunicación por SMS
File Encryption & Vault:
  name: Cifrado de archivos y bóvedas
  description: Cifra, bloquea y oculta archivos y carpetas privados
Password & 2FA:
  name: Contraseñas y segundo factor de autenticación
  description: Administradores de contraseñas, autenticadores, OTP, TOTP, HOTP, U2F, FIDO y herramientas de seguridad de dos factores
Browser:
  name: Navegador
  description: Navegadores web para surfear el internet y ver páginas web
App Store & Updater:
  name: Tienda de aplicaciones y actualizadores
  description: Descubrir, instalar y actualizar aplicaciones desde repositorios de software
News:
  name: Novedades
  description: Últimas noticias, artículos, fuentes RSS y agregadores de noticias
Local Media Player:
  name: Reproductor local
  description: Reproduce sin conexión archivos de audio y vídeo almacenados en tu dispositivo
Keyboard & IME:
  name: Teclado y métodos de entrada (IME)
  description: Teclados personalizados, métodos de entrada, auto‐corrección y aplicaciones de escritura
Social Network:
  name: Redes sociales
  description: Redes sociales, microblogueo, y plataformas de comunidades en línea
Podcast:
  name: Pódcast
  description: Suscríbete a, streaming y descarga episodios y programas de audio podcast
Weather:
  name: El tiempo y previsiones
  description: Aplicaciones de pronóstico, radar, temperatura y afección atmosférica
Online Media Player:
  name: Reproductor en línea
  description: Transmitir música, videos y contenido en vivo desde internet
Workout:
  name: Ejercicio físico
  description: Rutinas de ejercicio, seguimiento de gimnasio, running y aplicaciones de entrenamiento
Wallpaper:
  name: Fondos de pantalla
  description: Aplicaciones de fondos de pantalla estáticos y animados para la pantalla de inicio y bloqueo
Wallet:
  name: Cartera
  description: Carteras digitales para pagos, tarjetas y gestión de criptomonedas
Voice & Video Chat:
  name: Chat de vídeo y voz
  description: Aplicaciones de comunicación de audio y vídeo, conferencias y VoIP
Unit Convertor:
  name: Conversión de unidades
  description: Convertir entre unidades de longitud, peso, temperatura, moneda y más
Translation & Dictionary:
  name: Traducción y diccionarios
  description: Traducir idiomas, buscar palabras, y acceder a referencias de vocabulario
Text Editor:
  name: Editor de textos
  description: Editores de texto plano, Editores Markdown, y herramientas de escritura
Bookmark:
  name: Marcadores
  description: Guardar, organizar y administrar enlaces favoritos y listas de lectura
Calculator:
  name: Calculadora
  description: Herramientas para cálculos aritméticos, científicos y matemáticas
Calendar & Agenda:
  name: Calendarios y agendas
  description: Planificar eventos, recordatorios, citas y planes diarios
Cloud Storage & File Sync:
  name: Subir y sincronizar archivos
  description: Respalda, sincroniza y accede a tus archivos de forma remota a través de servicios en la nube
Draw:
  name: Dibujo
  description: Aplicaciones para bosquejo, pintar, ilustrar y crear arte digital
Ebook Reader:
  name: Lector de libro-e
  description: Lee libros-e EPUB, PDF y libros digitales y publicaciones
Finance Manager:
  name: Contabilidad y finanzas
  description: Controla los gastos, presupuestos, ingresos y las cuentas financieras personales
Gallery:
  name: Galería
  description: Explora, visualiza y organiza fotos, imágenes y vídeos
Icon Pack:
  name: Paquete de iconos
  description: Conjuntos de iconos personalizados para personalizar el estilo y el tema de los iconos de las aplicaciones
Launcher:
  name: Lanzador de aplicaciones
  description: Reemplazo de la pantalla de inicio y aplicaciones de entorno de escritorio
Note:
  name: Notas
  description: Cuadernos, memorándum y aplicaciones para tomar y organizar notas rápidamente
Pass Wallet:
  name: Billetes de transporte y entradas
  description: Guardar pases de embarque, boletos, tarjetas de fidelidad y cupones
Recipe Manager:
  name: Recetas de cocina
  description: Almacene, organice y descubra recetas de cocina e ideas de comida
Public Transport:
  name: Transporte público
  description: Bus, tren, metro, horarios de tránsito y planificadores de viaje
Shopping List:
  name: Lista de la compra
  description: Listas de comestibles, rastreadores de compras y aplicaciones de compras colaborativas
Task:
  name: Tareas
  description: Listas de cosas por hacer, gestores de tareas, herramientas de productividad, herramientas GTD
Forum:
  name: Foros
  description: Foros de discusión, hilos de la comunidad y plataformas de PyR
Habit Tracker:
  name: Seguimiento de hábitos
  description: Construye rutinas, realiza un seguimiento de tus objetivos diarios y controla tus rachas personales
Location Tracker & Sharer:
  name: Seguir y compartir mi ubicación
  description: Comparte y monitoriza el lugar de GPS en tiempo real con otros
Music Practice Tool:
  name: Práctica musical
  description: Afinadores, metrónomos, herramientas para acordes y ayudas para la práctica de instrumentos
AI Chat:
  name: Chat de IA
  description: Asistentes de IA, chatbots e interfaces de modelos de lenguaje a gran escala (LLM)
App Manager:
  name: Gestor de aplicaciones
  description: Gestiona, organiza y controla las aplicaciones instaladas, las intenciones y los permisos
Religion:
  name: Religión
  description: Tiempos de oración, textos santos, devocionales y aplicaciones de práctica espiritual
Clock:
  name: Reloj
  description: Indicar la hora actual
Contact:
  name: Contactos
  description: Aplicaciones de agenda de contactos, directorio telefónico y gestión de personas
Firewall:
  name: Cortafuegos
  description: Bloquea el tráfico de red no deseado y controla el acceso a Internet de la aplicación
Inventory:
  name: Inventario
  description: Realizar el seguimiento, catalogar y gestionar los artículos físicos y el inventario
Network Analyzer:
  name: Diagnósticos de red
  description: Diagnosticar Wi-Fi, escanear redes y monitorizar el rendimiento de la conexión
Battery:
  name: Batería
  description: Monitorizar y optimizar la vida de batería, uso de energía y carga
Flashlight:
  name: Linterna
  description: Aplicaciones de linterna y luz LED
Remote Access:
  name: Acceso Remoto
  description: Control de escritorios, servidores y dispositivos a distancia a través de RDP, VNC o SSH
Radio:
  name: Radio
  description: Transmite en directo emisoras de radio FM/AM y programas de radio por internet
Remote Controller:
  name: Mando a Distancia
  description: IR y mandos inteligentes para TV, unidades AC y otros dispositivos
Diet:
  name: Dieta
  description: Nutrición, calorias, gestión de comida y rastreador
Action Game:
  name: Juegos de acción
  description: Juegos de acción, deportes, carreras y de plataformas
Board Game:
  name: Juegos de mesa
  description: Juegos de mesa, ajedrez, go y tres en raya
Card Game:
  name: Juegos de cartas
  description: Juegos de cartas, solitario
Casual Game:
  name: Juegos casuales
  description: Juegos casuales simples
Dice:
  name: Dados
  description: Selección aleatoria
Download:
  name: Descargar
  description: Descargadores, gestores de descargas y clientes torrent
Educational Game:
  name: Juegos educativos
  description: Aprende jugando, quiz
Emulator:
  name: Emulador
  description: Emuladores para juegos y programas
File Manager:
  name: Administrador de archivos
  description: Exploradores y administradores de archivos
Game Helper:
  name: Ayudas para juegos
  description: Ayudas, asistentes, compañero, marcador y temporizadores para juegos
Health Manager:
  name: Gestor de salud
  description: Peso del administrador, frecuencia cardíaca, presión arterial, menstruación y otras métricas de salud
Alarm Clock:
  name: Reloj despertador
  description: Establecer una alarma
Camera:
  name: Cámara
  description: Cámara, visor de cámaras IP y grabadora de vídeo
Cast:
  name: Transmitir
  description: Transmitir, UPnP, DLNA, FCast, AirPlay, Miracast
Lyrics:
  description: Ver y buscar letras
  name: Letras
Market & Price:
  name: Mercado y precios
  description: Precio, tipo de cambio, acciones
Meditation:
  name: Meditación
  description: Meditación, atención plena, práctica respiratoria
Notification:
  name: Notificación
  description: Administrador de notificaciones, registrador, redirector, potenciador
Code & Forge:
  name: Código y forja
  description: Git, alojamiento del código fuente, forja
OCR:
  name: OCR
  description: Escáner de documentos, reconocimiento de caracteres ópticos
Party Game:
  name: Juego de Fiesta
  description: Multi-jugador, Juego de Fiesta
Platformer Game:
  name: Juego de plataformas
  description: Plataformas, juego de desplazamiento lateral
Push:
  name: Push
  description: Mensajes push
Puzzle Game:
  name: Juego de rompecabezas
  description: Rompecabezas, sudoku, juego de memoria
Recorder:
  name: Grabadora
  description: Audio, pantalla, grabadora de llamadas
Role-Playing Game:
  name: Juego de roles
  description: RPG, rogue-like
Schedule:
  name: Horario
  description: Horario para conferencia y evento
Shooter Game:
  name: Juego de disparos
  description: Juego de tiro al blanco
Strategy Game:
  name: Juego de estrategia
  description: Estrategia, simulación
Sport Game:
  name: Juego de Deporte
  description: Juegos de Deporte
Stopwatch:
  name: Cronómetro
  description: Medir el progreso, transcurrido, temporizador de vueltas
Text to Speech:
  name: Texto a Voz
  description: Herramientas TTS
Time Tracker:
  name: Registrador de tiempo
  description: Uso del registrador de tiempo en actividades y tiempo en pantalla
Timer:
  name: Temporizador
Visual Novel:
  name: Novela visual
  description: Novela visual, Simulador de citas, Juego de Historia
Volume:
  name: Volumen
  description: Gestión del volumen
Word Game:
  name: Juego de Palabra
  description: Juego de Rompecabezas, crucigrama, adivina la palabra
