Ads:
  description: Appen inneheld reklame
  name: Reklame
DisabledAlgorithm:
  description: Appen har ein svak tryggleikssignatur
  name: Signert med ein utrygg algoritme
KnownVuln:
  description: Appen inneheld eit kjent tryggleikshòl
  name: Kjent tryggleikshòl
NoSourceSince:
  name: Kjeldekode ikkje lenger tilgjengeleg
  description: Kjeldekoden er ikkje lenger tilgjengeleg, så det er ikkje mogleg med oppdatering
NonFreeAdd:
  description: Appen marknadsfører ufrie tillegg
  name: Ufrie tillegg
NonFreeAssets:
  description: Appen inneheld ufrie medie­ressursar
  name: Ufrie medie­ressursar
NonFreeDep:
  description: Appen er avhengig av andre ufrie appar
  name: Ufrie avhengnadar
NonFreeNet:
  description: Appen marknadsfører eller er heilt avhengig av ufrie nett-tenester
  name: Ufrie nett-tenester
Tracking:
  description: Appen sporar og rapporterer aktiviteten din
  name: Brukarsporing
TetheredNet:
  description: Appen er heilt avhengig av ein spesifikk instans av ei nett-teneste
  name: Låst til nett-teneste
