Categories:
  - Health Manager
License: MIT
AuthorName: XiaochangXu
SourceCode: https://github.com/XiaochangXu/HeartRateMonitor-composeui
IssueTracker: https://github.com/XiaochangXu/HeartRateMonitor-composeui/issues
Changelog: https://github.com/XiaochangXu/HeartRateMonitor-composeui/releases

AutoName: Heart Rate Monitor

RepoType: git
Repo: https://github.com/XiaochangXu/HeartRateMonitor-composeui.git
Binaries: 
  https://github.com/XiaochangXu/HeartRateMonitor-composeui/releases/download/v%v/app-release.apk

Builds:
  - versionName: '4.4'
    versionCode: 38
    commit: 29cd6b65c0ac8ca7cd0b285d413365af8cc1caec
    subdir: app
    gradle:
      - yes
    ndk: r28c

  - versionName: '4.5'
    versionCode: 39
    commit: 3fd1f4dced5405c098b9e112f534aaf9adc5fe27
    subdir: android/app
    gradle:
      - yes
    ndk: r28c

  - versionName: '4.6'
    versionCode: 40
    commit: 097cb14d4c4cabb40b5b6c279674a85076e36663
    subdir: android/app
    gradle:
      - yes
    ndk: r28c

  - versionName: '4.8'
    versionCode: 42
    commit: 6f5c2c601cfb1a9aea9a389436bb319c42f10a5b
    subdir: android/app
    gradle:
      - yes
    ndk: r28c

  - versionName: 4.8.6
    versionCode: 48
    commit: f4ece63c3972d0efb7d4d36e083ebb1bb87b6ecf
    subdir: android/app
    gradle:
      - yes
    ndk: r28c

  - versionName: 4.8.9
    versionCode: 51
    commit: 83234ff7f688a5e63bd7d84d9744d6adf8ac1f19
    subdir: android/app
    gradle:
      - yes
    ndk: r28c

  - versionName: 4.9.0
    versionCode: 52
    commit: 6f202bce37cc46c7cedb0ff970dac6d3ed88473d
    subdir: android/app
    gradle:
      - yes
    ndk: r28c

  - versionName: 4.9.2
    versionCode: 54
    commit: 9aaeadfcd83cbe0d2f54f234788b84af5f5f8159
    subdir: android/app
    gradle:
      - yes
    ndk: r28c

  - versionName: 4.9.3
    versionCode: 55
    commit: e83e1a41aff23bbb9ba5540f0856c2f0e78824d5
    subdir: android/app
    gradle:
      - yes
    ndk: r28c

AllowedAPKSigningKeys: a7518bd7a3ae60bb1cb8329160337f51f271eab3ab9409818a7a4bba074aa906

AutoUpdateMode: Version
UpdateCheckMode: Tags
CurrentVersion: 4.9.3
CurrentVersionCode: 55
