Connectivity:
  name: Comas-ceangail
Development:
  name: Leasachadh
Graphics:
  name: Grafaigeachd
Internet:
  name: Eadar-lìon
Multimedia:
  name: Meadhanan
Navigation:
  name: Seòladaireachd
Phone & SMS:
  name: Fòn ⁊ SMS
Reading:
  name: Leughadh
Science & Education:
  name: Saidheans ⁊ foghlam
Security:
  name: Tèarainteachd
Sports & Health:
  name: Spòrs ⁊ slàinte
System:
  name: An siostam
Theming:
  name: Ùrlaran
Writing:
  name: Sgrìobhadh
