Connectivity:
  name: Повезивање
Development:
  name: Развој
  description: Програмирање, кодирање, развојна окружења и развојни алат
Graphics:
  name: Графика
  description: Обрада слика, управљање сликама и прибор за творбу слика
Internet:
  name: Интернет
Multimedia:
  name: Мултимедија
Navigation:
  name: Навигација
Phone & SMS:
  name: Телефон и SMS
Reading:
  name: Читање
Science & Education:
  name: Наука и образовање
Security:
  name: Безбедност
Sports & Health:
  name: Спорт и здравље
System:
  name: Систем
Theming:
  name: Теме
Writing:
  name: Писање
App Store & Updater:
  name: Складиште и надграђивач програма
  description: Откриј, угради и надгради програме из складишта програма
Bookmark:
  name: Забелешка
  description: Чувај, уреди и управљај омиљеним везама и списковима за читање
Browser:
  name: Прегледник
  description: Прегледници мреже за једрење интернетом и преглед страница на мрежи
Calculator:
  name: Рачунар
  description: Бројчани, научни и математички прорачунски алати
Calendar & Agenda:
  name: Календар и роковник
  description: Заказани догађаји, подсетници, састанци и дневни роковници
Cloud Storage & File Sync:
  name: Складиште у облаку и усклађивање датотека
  description: Чување, усклађивање и удаљени приступ датотекама преко услуга облака
DNS & Hosts:
  name: ДНС и домаћини
  description: Поставке разрешивача ДНС-а, спречавање додатака, датотека домаћина и областно преусмеравање
Draw:
  name: Цртање
  description: Цртање, сликање, и дигитална уметност
Ebook Reader:
  name: Читач е-књига
  description: Читање електронских књига, ЕПУБ, ПДФ, дигиталне књиге и издања
Email:
  name: Е-пошта
  description: Странке е-поште за слање, пријем и управљање порукама е-поште
File Encryption & Vault:
  name: Шифровање и складиштење датотека
  description: Шифровање, закључавање личних датотека и омота
File Transfer:
  name: Пренос датотека
  description: Дељење и пренос датотека преко ФТП-а, ЛАН-а, Блутута и тачке до тачке П2П
Finance Manager:
  name: Управник новцем
  description: Праћење трошкова, имовине, приноса, и лични новчани налози
Gallery:
  name: Излог слика
  description: Преглед, претрага, разврставање слика, фотографија и видеа
Icon Pack:
  name: Омот сличица
Keyboard & IME:
  name: Тастатура и начин уноса
Launcher:
  name: Покретач
Local Media Player:
  name: Местни извођач садржаја
Messaging:
  name: Поруке
News:
  name: Вести
Note:
  name: Белешка
Online Media Player:
  name: Мрежни извођач садржаја
Pass Wallet:
  name: Новчаник лозинки
Password & 2FA:
  name: Лозинке и двострука пријава
Public Transport:
  name: Карта и ред вожње јавног превоза
Recipe Manager:
  name: Управник упутства
Shopping List:
  name: Списак за куповину
Social Network:
  name: Друштвена мрежа
Task:
  name: Задатак
Text Editor:
  name: Управник писања
Translation & Dictionary:
  name: Превод и речник
Unit Convertor:
  name: Претварач јединца
Voice & Video Chat:
  name: Ћаскање гласом и видеом
VPN & Proxy:
  name: Нестварна лична мрежа и посредник
Wallet:
  name: Новчаник
Wallpaper:
  name: Позадинска слика
Weather:
  name: Временске прилике
Workout:
  name: Вежбање
Podcast:
  name: Довод
AI Chat:
  name: Ћаскање са вештачким паметњаковићем
  description: Паметни вештачки помоћници, роботи за ћаскања, и сучеља великих језичких модела (ЛЛМ)
App Manager:
  name: Управник програма
  description: Управљање, устројство и надзор над уграђеним програмима, садржајима, дозволама
Clock:
  name: Часовник
  description: Аларм, стоперица, мерач времена и светски часовници
Contact:
  name: Додир
  description: Адресар, телефонски именик и програм за управљање познаницима
Battery:
  name: Батерија
  description: Надгледај и дотерај век батерије, употребу снаге и пуњење
Forum:
  name: Збор
  description: Зборови, предмети друштвених разговора, окрузи питања и одоговра
Diet:
  name: Исхрана
  description: Хранљивост, калорије, управљање и праћење исхране
Firewall:
  name: Ватрени зид
  description: Заустављање нежељеног мрежног саобраћаја и управљање мрежног приступа програма
Flashlight:
  name: Лампе
  description: Програми сијалица и лампи
Habit Tracker:
  name: Праћење навика
