Connectivity:
  name: Связь
Development:
  name: Разработка
  description: Кодирование, программирование, IDE, терминалы и инструменты разработчика
Graphics:
  name: Графика
  description: Редактирование картинок, фото, и инструменты визуального дизайна
Internet:
  name: Интернет
Multimedia:
  name: Мультимедиа
Navigation:
  name: Навигация
  description: Карты, GPS, навигатор и приложения для планирования маршрута
Phone & SMS:
  name: Телефон и SMS
  description: Набор номера, диспетчер вызовов и утилиты для обмена сообщениями
Reading:
  name: Чтение
Science & Education:
  name: Наука и образование
  description: Приложения для учёбы, изучения чего-либо и образования
Security:
  name: Безопасность
Sports & Health:
  name: Спорт и здоровье
System:
  name: Системные
Theming:
  name: Темы
  description: Настройте вид вашего устройства с помощью тем, шрифтов и стилей интерфейса
Writing:
  name: Офис
  description: Текстовые редакторы, приложения для ведения журналов, черчения и написания длинных текстов
DNS & Hosts:
  name: DNS и хосты
  description: Настройка DNS, блокировки рекламы, файла hosts, и маршрутизации домена
Email:
  name: Электронная почта
  description: Почтовые клиенты для отправки, приема и управления сообщениями электронной почты
VPN & Proxy:
  name: VPN и прокси
  description: Шифруйте трафик, обходите ограничения и анонимизируйте ваше подключение
Browser:
  name: Браузер
  description: Веб-браузеры для серфинга в интернете и просмотра сайтов
Calculator:
  name: Калькулятор
  description: Инструменты арифметических, научных и математических вычислений
Cloud Storage & File Sync:
  name: Хранение и синхронизация
  description: Резервное копирование, синхронизация и удаленный доступ к файлам через облачные сервисы
Ebook Reader:
  name: Читалки
  description: Чтение электронных книг, EPUB, PDF, и цифровых книг и публикаций
File Encryption & Vault:
  name: Шифрование файлов
  description: Шифрование, блокировка и скрытие личных файлов и папок
Finance Manager:
  name: Финансовый менеджер
  description: Отслеживание расходов, бюджетов, доходов и личных финансовых счетов
Gallery:
  name: Галерея
  description: Приложение для просматривания и упорядочивания фото, картинок и видео
File Transfer:
  name: Передача файлов
  description: Общий доступ и передача файлов по FTP, локальной сети, Bluetooth или peer-to-peer (p2p)
Launcher:
  name: Лаунчер
  description: Замены для главного экрана и приложения для окружения рабочего стола
Local Media Player:
  name: Медиаплееры
  description: Прослушивание аудио и просмотр видео, загруженных на ваше устройство
Messaging:
  name: Сообщения
  description: Приложения для быстрого общения, переписки, коротких сообщений и других коммуникаций
News:
  name: Новости
  description: Последние новости, статьи, ленты RSS и агрегаторы новостей
Note:
  name: Заметки
  description: Блокноты, заметки и приложения для быстрого ведения и организации заметок
Online Media Player:
  name: Онлайн-медиаплееры
  description: Трансляция музыки, видео и живого контента из интернета
Password & 2FA:
  name: Пароли и авторизация
  description: Менеджеры паролей, аутентификаторы, OTP, TOTP, HOTP, U2F, FIDO и инструменты для двухфакторной аутентификации
Podcast:
  name: Подкасты
  description: Подписка на подкасты и шоу, их трансляция и скачивание
Public Transport:
  name: Транспорт и расписания
  description: Автобусы, поезда, метро, расписание транспорта и планировщики поездок
Recipe Manager:
  name: Рецепты
  description: Хранение, сортировка и открытие новых рецептов и идей для блюд
Shopping List:
  name: Список покупок
Weather:
  name: Погода
  description: Прогноз погоды, радар, температура и приложения для отслеживания состояния атмосферы
Wallet:
  name: Кошельки
  description: Цифровые кошельки для платежей, карт и управления криптовалютой
Bookmark:
  name: Закладка
  description: Сохранение, организация и управление избранными ссылками и списками для чтения
Draw:
  name: Рисование
  description: Приложения для рисования эскизов, живописи, иллюстраций и работы с цифровым холстом
Wallpaper:
  name: Обои
  description: Обои для главного экрана и экрана блокировки, приложения с живыми обоями
Workout:
  name: Тренировки
  description: Программы для выполнения упражнений, отслеживания занятий в тренажерном зале, приложения для бега и фитнес-тренировок
Task:
  name: Задачи
  description: Списки дел, менеджеры задач и инструменты для продуктивности и GTD
Social Network:
  name: Соцсети
App Store & Updater:
  name: Магазин приложений и обновления
  description: Поиск, установка и обновление приложений из репозиториев программного обеспечения
Calendar & Agenda:
  name: Календари и ежедневники
  description: Планирование мероприятий, напоминания, встречи и ежедневники
Icon Pack:
  name: Наборы значков
  description: Авторские наборы значков, стилей и тем оформления приложений
Keyboard & IME:
  name: Клавиатуры и ввод
  description: Нестандартные клавиатуры, приложения для ввода данных, автоисправления и набора текста
Text Editor:
  name: Текстовые редакторы
  description: Редакторы текста, редакторы Markdown и инструменты для писательства
Translation & Dictionary:
  name: Перевод и словари
  description: Переводите языки, ищите слова и получайте доступ к словарям
Unit Convertor:
  name: Перевод единиц
  description: Преобразование единиц длины, веса, температуры, валют и прочего
Voice & Video Chat:
  name: Голосовые и видеочаты
  description: Звонки и видеозвонки, конференц-связь и приложения для коммуникации по VoIP
Pass Wallet:
  name: Кошелек
  description: Хранилище пропусков, билетов, карт лояльности и купонов
Forum:
  name: Форум
  description: Форумы, ветки обсуждений и платформы вопросов-ответов
Habit Tracker:
  name: Трекер привычек
  description: Формирование распорядка дня, отслеживание ежедневных целей, отслеживание личных достижений
Music Practice Tool:
  name: Инструмент для музыкальной практики
  description: Тюнеры, метрономы, инструменты для аккордов и помощники для практики игры на музыкальных инструментах
Location Tracker & Sharer:
  name: Отслеживание и публикация местоположения
  description: Делитесь с другими своей геопозицией в реальном времени
AI Chat:
  name: Чаты с ИИ
  description: ИИ-помощники, чат-боты и интерфейсы больших языковых моделей (LLM)
App Manager:
  name: Менеджер приложений
  description: Управление, организация и контроль установленных приложений, взаимодействий, разрешений
Religion:
  name: Религия
  description: Таймеры для молитв, священные тексты и приложения для духовных практик
Clock:
  name: Часы
  description: Определите текущее время
Contact:
  name: Контакты
  description: Адресная книга, телефонная книга и приложения для управления персоналом
Firewall:
  name: Брандмауэр
  description: Блокировка нежелательного сетевого трафика, и контроль доступа приложений в Интернет
Network Analyzer:
  name: Сетевой анализатор
  description: Диагностика Wi-Fi, сканирование локальных сетей, мониторинг скорости соединения
Flashlight:
  name: Фонарик
  description: Приложения для работы с фонариками и светодиодными вспышками
Inventory:
  name: Инвентарь
  description: Отслеживание, систематизация и управление товарами и запасами
Radio:
  name: Радио
  description: Трансляция радиостанций и интернет-радиотрансляций
Remote Controller:
  name: Пульт дистанционного управления
  description: ИК-пульты и пульты умного дома для телевизоров, кондиционеров и других устройств
Battery:
  name: Батарея
  description: Отслеживание и оптимизация срока службы батареи, энергопотребления и зарядки
Remote Access:
  name: Удаленный доступ
  description: Управляйте компьютерами, серверами и устройствами удаленно через RDP, VNC или SSH
Action Game:
  name: Экшен-игра
  description: Экшен, спорт, гонки и платформеры
Board Game:
  name: Настольная игра
  description: Настольная игра, шахматы, го, крестики-нолики
Card Game:
  name: Карточная игра
  description: Карточная игра, пасьянс
Casual Game:
  name: Казуальная игра
  description: Простая казуальная игра
Dice:
  name: Игральные кости
  description: Случайный выделитель
Diet:
  name: Диета
  description: Питание, калории, управление и трекинг еды
Educational Game:
  name: Образовательная игра
  description: Внутриигровое обучение, викторины
Emulator:
  name: Эмулятор
  description: Эмулятор для игр и программ
Game Helper:
  name: Игровой помощник
  description: Игровой помощник, ассистент, компаньон, табло, таймер
Party Game:
  description: Командная игра, игра для вечеринки с гостями
  name: Игры для компании
Meditation:
  name: Медитация
  description: Медиация, концентрация, дыхательная практика
Health Manager:
  name: Отслеживание здоровья
  description: Отслеживание веса, пульса, давления, менструации и других метрик здоровья
Download:
  name: Скачивание
  description: Загрузчик, менеджер загрузок и торрент-клиент
File Manager:
  name: Файловый Менеджер
  description: Файловый менеджер и проводник
Platformer Game:
  name: Платформеры
  description: Платформеры, игры с боковой прокруткой
Puzzle Game:
  name: Пазлы
  description: Пазлы, судоку, игры на память
Role-Playing Game:
  name: Ролевые игры
  description: РПГ, роуглайки
Shooter Game:
  name: Шутеры
Strategy Game:
  name: Стратегии
  description: Стратегии, симуляторы
Sport Game:
  name: Спортивные игры
  description: Игры о спорте
Text to Speech:
  name: Текст в Речь
  description: Инструменты для преобразования текста в речь
Visual Novel:
  name: Визуальная новелла
  description: Визуальная новелла, galgame, сюжетная игра
Word Game:
  name: Словесные Игры
  description: Головоломки со словами, кроссворды, угадывание слов
Timer:
  name: Таймер
Alarm Clock:
  name: Будильник
  description: Установить будильник на определённое время
Camera:
  name: Камера
  description: Камера, средства для просмотра IP-камер и видеорегистратор
Cast:
  name: Трансляция
  description: Трансляция, UPnP, DLNA, FCast, AirPlay, Miracast
Lyrics:
  name: Текст песни
  description: Просмотр и поиск текстов песен
Market & Price:
  name: Рынок и цена
  description: Цена, обменный курс, акции
Notification:
  name: Уведомление
  description: Менеджер уведомлений, журнал, перенаправитель, усилитель
