Ads:
  description: Aplikazio honek iragarkiak ditu
  name: Iragarkiak
DisabledAlgorithm:
  description: Aplikazio honek segurtasun sinadura ahula du
  name: Segurua ez den algoritmo batez sinatua
KnownVuln:
  description: Aplikazio honek segurtasun arazo ezagun bat du
  name: Ahultasun ezaguna
NoSourceSince:
  name: 'Iturburu koderik ez data honetatik:'
  description: Iturburu kodea ez dago jada eskuragarri, ezin izango da eguneratu
NonFreeAdd:
  description: Aplikazio honen libreak ez diren gehigarriak bultzatzen ditu
  name: Libreak ez diren gehigarriak
NonFreeAssets:
  description: Aplikazio honek baliabide ez libreak ditu
  name: Libreak ez diren baliabideak
NonFreeDep:
  description: Aplikazio hau beste aplikazio ez libreen menpekoa da
  name: Libreak ez diren menpekotasunak
NonFreeNet:
  description: Aplikazio honek sare zerbitzu ez libreak sustatzen ditu edo haiekiko menpekotasun osoa du
  name: Libreak ez diren sareko zerbitzuak
Tracking:
  description: Aplikazio honek zure jardueraren jarraipena egiten du eta berri ematen du
  name: Arrastoaren jarraipena
TetheredNet:
  description: Aplikazio honek sareko zerbitzu baten instantzia batekiko menpekotasun osoa du
