Connectivity:
  name: Sareak
Development:
  name: Garapena
Graphics:
  name: Grafikoak
Internet:
  name: Internet
Multimedia:
  name: Multimedia
Navigation:
  name: Orientazioa
Phone & SMS:
  name: Telefonoa eta SMS
Reading:
  name: Irakurketa
Science & Education:
  name: Zientzia eta hezkuntza
Security:
  name: Segurtasuna
Sports & Health:
  name: Kirola eta osasuna
System:
  name: Sistema
Theming:
  name: Itxura
Writing:
  name: Idazketa
Action Game:
  name: Ekintza-jokoa
  description: Ekintza, kirol, lasterketa eta plataforma-jokoak
AI Chat:
  name: AA txata
  description: AA laguntzaileak, txatbotak eta hizkuntza eredu handien (LLM) interfazeak
Alarm Clock:
  name: Alarma-erlojua
  description: Ezarri alarma bat ordu batean
Ambient Sound:
  name: Giro-soinua
  description: Erreproduzitu giro-soinua, zarata
App Manager:
  name: Aplikazio-kudeatzailea
  description: Kudeatu, antolatu eta kontrolatu instalatutako aplikazioak, intent-ak, baimenak
App Store & Updater:
  name: Aplikazio denda eta eguneratzailea
  description: Aurkitu, instalatu eta eguneratu aplikazioak software-biltegietatik
Audiobook:
  name: Audio-liburuak
  description: Audio-liburu kudeatzailea eta erreproduzitzailea
Battery:
  name: Bateria
  description: Kontrolatu eta optimizatu bateriaren bizitza, energia erabilera eta kargatzea
Board Game:
  name: Mahai-jokoa
  description: Mahai-jokoa, xakea, go, artzain-jokoa
Bookmark:
  name: Laster-markak
  description: Gorde, antolatu eta kudeatu gogoko esteka eta irakurketa-zerrendak
Browser:
  name: Nabigatzailea
  description: Web nabigatzaileak, Interneten nabigatu eta webguneak ikusteko
Calculator:
  name: Kalkulagailua
  description: Kalkulu aritmetiko, zientifiko eta matematikoak egiteko tresnak
Calendar & Agenda:
  name: Egutegia eta agenda
  description: Antolatu gertaerak, oroigarriak, hitzorduak eta eguneroko planifikatzaileak
Camera:
  name: Kamera
  description: Kamera, IP kamera ikustaila eta bideo-grabatzailea
Card Game:
  name: Karta-jokoa
  description: Karta-jokoa, bakar-jokoa
Clock:
  name: Erlojua
  description: Uneko ordua jakiteko
Contact:
  name: Kontaktuak
  description: Helbide-liburuak, telefono-aurkibideak eta pertsonak kudeatzeko aplikazioak
Covid:
  name: Covid
