#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

# Redirect output to stderr.
exec 1>&2

apps="$(git diff --cached --name-only --diff-filter=ACM | sed -n 's,metadata/\([^/]*\)\.txt,\1,p')"

if [[ -n "$apps" ]]; then
    fdroid lint -f $apps
fi
