#!/bin/sh

set -o errexit
set -o nounset
set -o pipefail

# Redirect output to stderr.
exec 1>&2


fdroid lint -f $(git diff --cached --name-only --diff-filter=ACM | sed -n 's@metadata/\(.*\).txt@\1@p')
