#!/bin/sh
#
# Simple pre-commit hook to check that there are no errors in the fdroid
# metadata files.

# Redirect output to stderr.
exec 1>&2

# If there are metadata errors, print the stack traces and fail.
exec fdroid readmeta
