Ads:
  description: Гэтая праграма змяшчае рэкламу
  name: Рэклама
DisabledAlgorithm:
  description: Гэтая праграма мае слабы подпіс бяспекі
  name: Падпісана праз небяспечны алгарытм
KnownVuln:
  description: Гэтая праграма змяшчае вядомую ўразлівасць бяспекі
  name: Ёсць уразлівасць
NoSourceSince:
  name: Зыходны код недаступны ад
  description: Зыходны код больш недаступны, абнаўленні немагчымыя
NonFreeAdd:
  description: Праграма прапаноўвае нявольныя дадаткі
  name: Нявольныя дадаткі
NonFreeAssets:
  description: Праграма змяшчае нявольнае змесціва
  name: Нявольнае змесціва
NonFreeDep:
  description: Праграма залежыць ад іншых нявольных праграм
  name: Нявольныя залежнасці
NonFreeNet:
  description: Праграма прапаноўвае нявольныя сеткавыя сэрвісы або залежыць ад іх
  name: Нявольныя сеткавыя сэрвісы
Tracking:
  description: Праграма адсочвае вашу актыўнасць
  name: Сачэнне
TetheredNet:
  description: Праграмма цалкам залежыць ад нейкай часткі сеткавага сэрвісу.
  name: Залежнасць ад сеткавых сэрвісаў
