Connectivity:
  name: Сувязь
Development:
  name: Распрацоўка
  description: Праграмаванне, IDE, тэрміналы, інструменты распрацоўшчыка
Graphics:
  name: Графіка
  description: Рэдагаванне выяў, апрацоўка фота, візуальны дызайн
Internet:
  name: Інтэрнэт
Multimedia:
  name: Мультымедыя
Navigation:
  name: Навігацыя
  description: Мапы, GPS, падрабязныя навігацыйныя інструкцыі, планаванне маршрутаў
Phone & SMS:
  name: Тэлефон і SMS
  description: Праграмы для тэлефанавання, менеджары выклікаў, інструменты для SMS
Reading:
  name: Чытанне
  description: Артыкулы, лонгрыды, адкладальнікі артыкулаў, чытальнікі
Science & Education:
  name: Навука і адукацыя
  description: Праграмы для навучання, адукацыі, навуковых тэкстаў
Security:
  name: Бяспека
Sports & Health:
  name: Спорт і здароўе
  description: Фітнэс-трэкінг, адсочванне стану здароўя, спартыўнай актыўнасці
System:
  name: Сістэма
Theming:
  name: Тэмы
  description: Дапасоўвайце выгляд сваёй прылады да свайго густу праз тэмы, шрыфты, стылі інтэрфейсу
Writing:
  name: Напісанне
  description: Тэкставыя працэсары, праграмы для дзённікаў, чарнавікоў, доўгіх тэкстаў
AI Chat:
  name: ШІ-чаты
  description: ШІ-асістэнты, чат-боты, інтэрфейсы вялікіх моўных мадэляў (LLM)
App Manager:
  name: Менеджары праграм
  description: Кантралюйце і арганізоўвайце ўсталяваныя праграмы, намеры, дазволы
App Store & Updater:
  name: Крамы праграм
  description: Шукайце, усталёўвайце, абнаўляйце праграмы з рэпазіторыяў
Battery:
  name: Батарэя
  description: Адсочвайце і аптымізуйце працу, выкарыстанне і зарадку батарэі
Bookmark:
  name: Закладкі
  description: Захоўвайце, арганізоўвайце, кіруйце абранымі спасылкамі і спісамі чытання
Browser:
  name: Браўзеры
  description: Вэб-браўзеры для інтэрнэт-сёрфінгу і прагляду сайтаў
Calculator:
  name: Калькулятары
  description: Інструменты арыфметычнага, навуковага, матэматычнага вылічэння
Calendar & Agenda:
  name: Календары і арганайзары
  description: Плануйце падзеі, сустрэчы, задавайце напаміны
Clock:
  name: Гадзіннікі
  description: Глядзіце, які цяпер час
Cloud Storage & File Sync:
  name: Воблака, сінхранізацыя
  description: Захоўвайце рэзервовыя копіі, сінхранізуйце файлы
Contact:
  name: Кантакты
  description: Адрасныя, тэлефонныя кнігі, упарадкаванне кантактаў
DNS & Hosts:
  name: DNS і хасты
  description: Наладжвайце рэзольвары DNS, блакіроўку рэкламы, файл hosts, маршрутызацыю даменаў
Draw:
  name: Маляванне
  description: Праграмы для скетчаў, паўнавартаснага малявання, ілюстравання, дыджытал-арту
Ebook Reader:
  name: Чытальнікі электронных кніг
  description: Чытайце EPUB, PDF, электронныя кнігі і публікацыіі
Email:
  name: Электронная пошта
  description: Кліенты для дасылання, атрымання электронных лістоў і кіравання імі
File Encryption & Vault:
  name: Шыфраванне файлаў і сховішча
  description: Шыфруйце, блакіруйце і хавайце прыватныя файлы і папкі
File Transfer:
  name: Перадача файлаў
  description: Абагульвайце і перадавайце файлы праз FTP, лакальную сетку, Bluetooth або наўпрост (P2P)
Finance Manager:
  name: Фінансавыя менеджары
  description: Адсочвайце выдаткі, бюджэты, прыбыткі, асабістыя фінансавыя лікі
Firewall:
  name: Заслоны
  description: Блакіруйце нежаданы трафік і кантралюйце доступ праграм да інтэрнэту
Flashlight:
  name: Ліхтарыкі
  description: Выкарыстоўвайце экран або святлодыёд прылады як ліхтарык
Forum:
  name: Форумы
  description: Дошкі для абмеркавання, супольныя трэды, платформы Q&A
Gallery:
  name: Галерэі
  description: Шукайце, праглядайце, упарадкоўвайце фотаздымкі, выявы, відэа
Icon Pack:
  name: Наборы значкоў
  description: Дапасоўвайце наборы значкоў і значкі праграм да свайго густу
Inventory:
  name: Інвентар
  description: Адсочвайце, каталагізуйце і кантралюйце сваю маёмасць
Keyboard & IME:
  name: Клавіятура і ўвод
  description: Уласныя клавіятуры, метады ўводу, аўтавыпраўленне
Launcher:
  name: Лаўнчары
  description: Замены хатніх экранаў, уласныя графічныя асяроддзі
Local Media Player:
  name: Афлайн-прайгравальнікі
  description: Слухайце музыку і глядзіце відэа з вашай прылады
Location Tracker & Sharer:
  name: Адсочванне і абагульванне месцазнаходжання
  description: Абагульвайце і адсочвайце месцазнаходжанне з іншымі людзьмі ў рэальным часе
Action Game:
  name: Экшн-гульні
  description: Экшн, спорт, гонкі, платформеры
Alarm Clock:
  name: Будзільнікі
  description: Паспявайце са справамі
Board Game:
  name: Настольныя гульні
  description: Настольныя гульні, шахматы, го, крыжыкі-нулікі
Camera:
  name: Камеры
  description: Камеры, праглядальнікі IP-камер, запіс відэа
Card Game:
  name: Карткавыя гульні
  description: Карткавыя гульні, саліцёр
Casual Game:
  name: Казуальныя гульні
  description: Простыя казуальныя гульні
Code & Forge:
  name: Кантроль кода
  description: Git, хостынг зыходнага кода
Dice:
  name: Жэрабя
  description: Генератары выпадковых лічбаў
Diet:
  name: Дыета
  description: Харчаванне, каларыйнасць, адсочванне ежы
Download:
  name: Сцягванне
  description: Сцягвальнікі, менеджары сцягвання, торэнт-кліенты
Educational Game:
  name: Адукацыйныя гульні
  description: Вучыцеся гуляючы
Emulator:
  name: Эмулятары
  description: Эмулятары для запуску гульняў і праграм
File Manager:
  name: Файлавыя менеджары
  description: Файлавыя менеджары і праваднікі
Game Helper:
  name: Гульнявыя памочнікі
  description: Гульнявыя дапаможнікі, асістэнты, кампаньёны, табліцы лікаў, таймеры
Habit Tracker:
  name: Трэкеры звычак
  description: Задавайце і адсочвайце штодзённыя мэты
Health Manager:
  name: Здароўе
  description: Сачыце за вагай, пульсам, крывяным ціскам, менструацыяй, іншымі метрыкамі здароўя
Lyrics:
  name: Тэксты песень
  description: Шукайце і чытайце тэксты песень
Market & Price:
  name: Рынак, кошты
  description: Цэны, абмен валют, акцыі
Meditation:
  name: Медытацыя
  description: Медытацыя, расслабленне, трэніроўка дыхання
Messaging:
  name: Гутарка
  description: Месенджары, чаты, SMS-праграмы
Music Practice Tool:
  name: Музычная практыка
  description: Цюнары, метраномы, вызначальнікі акордаў, практычныя памочнікі для ігры на інструментах
Network Analyzer:
  name: Сеткавыя аналізатары
  description: Дыягностыка Wi-Fi, сканаванне сетак, адсочванне якасці злучэння
News:
  name: Навіны
  description: Апошнія навіны, артыкулы, RSS-каналы, агрэгатары навін
Note:
  name: Нататкі
  description: Нататнікі, праграмы для запісак і арганайзары
Notification:
  name: Апавяшчэнні
  description: Менеджары, журналы, перанакіроўвальнікі, пашыральнікі апавяшчэнняў
OCR:
  name: Сканеры
  description: Сканеры дакументаў, распазнавальнікі сімвалаў
Online Media Player:
  name: Анлайн-прайгравальнікі
  description: Слухайце музыку, глядзіце відэа, жывыя эфіры з інтэрнэту
Party Game:
  name: Сумесныя гульні
  description: Гульні для некалькіх гульцоў
Pass Wallet:
  name: Квіткі
  description: Захоўвайце білеты на праезд, квіткі, карткі лаяльнасці, купоны
Password & 2FA:
  name: Паролі, аўтэнтыфікацыя
  description: Менеджары пароляў, аўтэнтыфікатары, OTP, TOTP, HOTP, U2F, FIDO, інструменты двухфактарнай праверкі спраўднасці
Platformer Game:
  name: Платформеры
  description: Гульні з платформінгам, сайд-скролеры
Podcast:
  name: Падкасты
  description: Падпісвайцеся на падкасты, слухайце і сцягвайце іх эпізоды
Public Transport:
  name: Грамадскі транспарт
  description: Аўтобусы, цягнікі, метро, расклады, планаванне шляху
Puzzle Game:
  name: Галаваломкі
  description: Галаваломкі, судоку, гульні на памяць
Radio:
  name: Радыё
  description: Слухайце FM- і AM- і інтэрнэт-радыёстанцыі ў жывым эфіры
Recipe Manager:
  name: Рэцэпты
  description: Захоўвайце, упарадкоўвайце і знаходзьце новыя рэцэпты і ідэі для страў
Recorder:
  name: Рэкордары
  description: Запіс гуку, экрана, выклікаў
Religion:
  name: Рэлігія
  description: Часы службаў, святыя тэксты, малітвы, духоўная практыка
Role-Playing Game:
  name: Ролевыя гульні
  description: RPG, «рагалікі»
Remote Access:
  name: Аддалены доступ
  description: Аддалена кіруйце камп'ютарамі, серверамі, прыладамі праз RDP, VNC або SSH
Remote Controller:
  name: Пульты
  description: ІЧ-пульты, пульты для разумных хат, тэлевізараў, кандыцыянераў, іншых прылад
Schedule:
  name: Планаванне
  description: Планаванне канферэнцый і падзей
Shooter Game:
  name: Шутары
  description: Гульні-«стралялкі»
Strategy Game:
  name: Стратэгіі
  description: Стратэгічныя гульні
Shopping List:
  name: Спісы пакупак
  description: Спісы прадуктаў, адсочванне пакупак, сумеснае куплянне
Social Network:
  name: Сацыяльныя сеткі
  description: Сацсеткі, мікраблогі, анлайн-платформы для супольнасці
Sport Game:
  name: Спартыўныя гульні
  description: Гульні на спартыўную тэматыку
Stopwatch:
  name: Секундамеры
  description: Вымярайце час на адзін круг прабежкі ці агульны час
Task:
  name: Заданні
  description: Спісы спраў, менеджары заданняў, інструменты прадукцыйнасці
Text Editor:
  name: Тэкставыя рэдактары
  description: Базавыя рэдактары, Markdown-рэдактары, інструменты напісання
Text to Speech:
  name: Тэкст у маўленне
  description: Інструменты ператварэння тэксту ў маўленне
Time Tracker:
  name: Трэкеры часу
  description: Адсочвайце, колькі часу вы выдаткоўваеце на актыўнасці і на сваю прыладу
Timer:
  name: Таймеры
  description: Інтэрвалы, разлік і адлік часу
Translation & Dictionary:
  name: Пераклады, слоўнікі
  description: Перакладайце тэксты, шукайце словы, праслухоўвайце іх вымаўленне
Unit Convertor:
  name: Канвертары адзінак
  description: Канвертуйце адзінкі даўжыні, вагі, тэмпературы, валюты і не толькі
Visual Novel:
  name: Візуальныя навелы
  description: Візуальныя навелы, бісёдзэ, гульні з вялікім акцэнтам на гісторыю
Voice & Video Chat:
  name: Галасавы, відэачат
  description: Праграмы для аўдыя- і відэасувязі, канферэнцый, VoIP-камунікацыі
Volume:
  name: Гучнасць
  description: Кіруйце наладамі гучнасці
VPN & Proxy:
  name: VPN і проксі
  description: Шыфруйце трафік, абыходзьце абмежаванні, ананімізоўвайце злучэнне
Wallet:
  name: Гаманцы
  description: Лічбавыя гаманцы для кіравання трансакцыямі, карткамі і крыптавалютамі
Wallpaper:
  name: Шпалеры
  description: Праграмы для змянення фону галоўнага экрана і экрана блакіроўкі
Weather:
  name: Надвор'е
  description: Прагнозы, радары, тэмпература, стан атмасферы
Word Game:
  name: Слоўныя гульні
  description: Галаваломкі са словамі, крыжаванкі
Workout:
  name: Трэніроўкі
  description: Планаванне размінак, адсочванне наведванняў спартыўнай залы, прабежак, фітнэс-трэніровак
Cast:
  name: Перадача экрана
  description: Трансляванне экрана, UPnP, DLNA, FCast, AirPlay, Miracast
Push:
  name: Адпраўшчыкі апавяшчэнняў
  description: Праграмы для дасылання push-апавяшчэнняў
