Connectivity:
  name: Сувязь
Development:
  name: Распрацоўка
Games:
  name: Гульні
Graphics:
  name: Графіка
Internet:
  name: Інтэрнэт
Money:
  name: Фінансы
Multimedia:
  name: Мультымедыя
Navigation:
  name: Навігацыя
Phone & SMS:
  name: Тэлефон і SMS
Reading:
  name: Чытанне
Science & Education:
  name: Навука і адукацыя
Security:
  name: Бяспека
Sports & Health:
  name: Спорт і здароўе
System:
  name: Сістэма
Theming:
  name: Тэмы
Time:
  name: Час
Writing:
  name: Напісанне
AI Chat:
  name: ШІ Размова
App Manager:
  name: Кіраўнік Праграм
App Store & Updater:
  name: App Store і абнаўленні
Battery:
  name: Батарэя
Bookmark:
  name: Закладка
Browser:
  name: Аглядальнік
Calculator:
  name: Калькулятар
Calendar & Agenda:
  name: Каляндар і парадак дня
Clock:
  name: Гадзіннік
Cloud Storage & File Sync:
  name: Воблачнае Сховішча і сінхранізацыя файлаў
Contact:
  name: Кантакты
DNS & Hosts:
  name: DNS і хасты
Draw:
  name: Маляванне
Ebook Reader:
  name: Чытальнікі электронных кніг
Email:
  name: Электронная пошта
File Encryption & Vault:
  name: Шыфраванне файлаў і сховішча
File Transfer:
  name: Перадача файлаў
Finance Manager:
  name: Кіраўнік Фінансаў
Firewall:
  name: Заслона
Flashlight:
  name: Ліхтарык
Forum:
  name: Форум
Gallery:
  name: Галерэя
Icon Pack:
  name: Пачкі значкоў
Inventory:
  name: Інвэнтар
Keyboard & IME:
  name: Клавіятура і ўвод
Launcher:
  name: Запускальнік
Local Media Player:
  name: Лакальны Медыя Прайгравальнік
Location Tracker & Sharer:
  name: Адсочванне і абагульванне месцазнаходжання
