Ads:
  description: Cette application contient des publicités.
  name: Publicités
DisabledAlgorithm:
  description: Cette application présente une signature de sécurité insuffisante.
  name: Signé à l'aide d'un algorithme non sécurisé
KnownVuln:
  description: Cette application présente une faille de sécurité connue.
  name: Vulnérabilité connue
NoSourceSince:
  name: Aucune source depuis
  description: Le code source n'est plus disponible, aucune mise à jour n'est possible
NonFreeAdd:
  description: Cette application fait la promotion d'extensions payantes
  name: Extensions payantes
NonFreeAssets:
  description: Cette application contient des éléments payants
  name: Composants propriétaires
NonFreeDep:
  description: Cette application nécessite d'autres applications payantes
  name: Dépendances propriétaires
NonFreeNet:
  description: Cette application fait la promotion d'un service réseau payant ou en dépend entièrement.
  name: Services réseau payants
Tracking:
  description: Cette application suit et rend compte de votre activité
  name: Suivi
TetheredNet:
  description: Cette application dépend entièrement d'une instance spécifique d'un service réseau
  name: Services réseau en mode filaire
