Connectivity:
  name: Connectivité
Development:
  name: Développement
  description: Codage, programmation, environnement de développement, terminal et outils de développement
Graphics:
  name: Graphisme
  description: Outils de retouche d'images, de manipulation de photos et de conception visuelle
Internet:
  name: Internet
Multimedia:
  name: Multimédia
Navigation:
  name: Navigation
  description: Applications de cartographie, de GPS, d'itinéraires détaillés et de planification d'itinéraires
Phone & SMS:
  name: Téléphone et SMS
  description: Compositeurs, gestionnaires d'appels et utilitaires de messagerie texte
Reading:
  name: Lecture
  description: Articles, contenus approfondis, applications de lecture différée et de lecture Web
Science & Education:
  name: Science et éducation
  description: Applications d'apprentissage, d'étude, de référence et éducatives
Security:
  name: Sécurité
Sports & Health:
  name: Sport et santé
  description: Suivi de l'activité physique, bien-être, résultats sportifs et suivi de la santé
System:
  name: Système
Theming:
  name: Personnalisation
  description: Personnalisez l'apparence de votre appareil avec des thèmes, des polices et des styles d'interface utilisateur
Time:
  name: Temps
  description: Convertisseurs de fuseaux horaires, horloges mondiales et outils de gestion du temps
Writing:
  name: Écriture
  description: Applications de traitement de texte, de journal intime, de rédaction et d'écriture de longs textes
Calendar & Agenda:
  name: Calendrier & Agenda
  description: Planifier des évènements, des rappels, des rendez-vous et les agendas
Cloud Storage & File Sync:
  name: Stockage dans le cloud & Synchronisation de fichiers
  description: Sauvegarde, synchronisation et accès distant aux fichiers via des services sur le cloud
Messaging:
  name: Messagerie
  description: Applications de messagerie instantanée, de chat et de SMS
News:
  name: Nouvelles
  description: Dernières actualités, articles, flux RSS et agrégateurs d'actualités
Social Network:
  name: Réseau social
  description: Réseaux sociaux, microblogging et plateformes communautaires en ligne
Wallet:
  name: Portefeuille
  description: Portefeuilles numériques pour les paiements, les cartes et la gestion des cryptomonnaies
Voice & Video Chat:
  name: Chat vocal & vidéo
  description: Applications d'appels audio et vidéo, de visioconférence et de communication VoIP
Online Media Player:
  name: Lecteur multimédia en ligne
  description: Écoutez de la musique, regardez des vidéos et suivez des contenus en direct sur Internet
Password & 2FA:
  name: Mot de passe & A2F
  description: Gestionnaires de mots de passe, applications d'authentification, OTP, TOTP, HOTP, U2F, FIDO et outils de sécurité à deux facteurs
Podcast:
  name: Podcast
  description: Abonnez-vous, écoutez en streaming et téléchargez des épisodes et des émissions de podcasts
Weather:
  name: Météo
  description: Applications de prévisions météo, de radar, de température et de conditions atmosphériques
VPN & Proxy:
  name: VPN & proxy
  description: Cryptez votre trafic, contournez les restrictions (contournement) et rendez votre connexion anonyme
DNS & Hosts:
  name: DNS & Hôtes
  description: Configurer les résolveurs DNS, le blocage des publicités, le fichier hosts et le routage des domaines
Email:
  name: E-mail
  description: Clients de courriel pour envoyer, recevoir et gérer des courriels
App Store & Updater:
  name: Boutique d'applications & programme de mise à jour
  description: Découvrir, installer et mettre à jour les applications depuis les dépôts logiciels
Browser:
  name: Navigateur
  description: Les navigateurs web pour naviguer sur internet et consulter les sites web
File Encryption & Vault:
  name: Chiffrement de fichiers & Coffre-fort
  description: Chiffrer, verrouiller et masquer des fichiers et dossiers privés
File Transfer:
  name: Transfert de fichiers
  description: Partager et transférer des fichiers via FTP, LAN, Bluetooth, ou pair-à-pair (p2p)
Keyboard & IME:
  name: Clavier & IME
  description: Claviers personnalisés, méthodes de saisie, correction automatique et applications de saisie
Local Media Player:
  name: Lecteur multimédia local
  description: Lire des fichiers audio et vidéo hors ligne stockés sur votre appareil
Bookmark:
  name: Signet
  description: Enregistrer, organiser et gérer les liens favoris et les listes de lecture
Calculator:
  name: Calculatrice
  description: Outils de calculs arithmétiques, scientifiques et mathématiques
Draw:
  name: Dessiner
  description: Applications de dessin, peinture, illustration et canevas d'art numérique
Ebook Reader:
  name: Liseuse électronique
  description: Lire des ebooks, EPUB, PDF, des livres et publications numériques
Finance Manager:
  name: Gestionnaire de finances
  description: Suivre les dépenses, les budgets, les revenus, et les comptes personnels de finances
Gallery:
  name: Galerie
  description: Parcourir, afficher et organiser des photos, des images et des vidéos
Icon Pack:
  name: Pack d'icônes
  description: Jeux d'icônes personnalisés pour personnaliser le style et le thème des icônes d'application
Launcher:
  name: Lanceur
  description: Remplacements d'écran d'accueil et applications d'environnement de bureau
Note:
  name: Note
  description: Blocs-notes, notes de service et applications pour prendre rapidement des notes et s'organiser
Pass Wallet:
  name: Portefeuille de pass
  description: Conservez vos cartes d'embarquement, vos billets, vos cartes de fidélité et vos bons de réduction
Recipe Manager:
  name: Gestionnaire de recettes
  description: Conservez, organisez et découvrez des recettes de cuisine et des idées de repas
Text Editor:
  name: Éditeur de texte
  description: Éditeurs de texte brut, éditeurs Markdown et outils de rédaction
Translation & Dictionary:
  name: Traduction & dictionnaire
  description: Traduire des textes, rechercher des mots et consulter des dictionnaires
Unit Convertor:
  name: Convertisseur d'unités
  description: Convertir des unités de longueur, de poids, de température, de devise et bien d'autres encore
Wallpaper:
  name: Fonds d'écran
  description: Applications pour fonds d'écran et fonds d'écran animés pour l'écran d'accueil et l'écran de verrouillage
Workout:
  name: Entraînement
  description: Programmes d'entraînement, suivi des séances de sport, course à pied et applications de remise en forme
Public Transport:
  name: Transports en commun
  description: Horaires des bus, trains, métros et transports en commun, ainsi que calculateurs d'itinéraires
Shopping List:
  name: Liste de courses
  description: Listes de courses, outils de suivi des achats et applications de courses collaboratives
Task:
  name: Tâche
  description: Listes de tâches, gestionnaires de tâches et outils de productivité et de gestion des tâches (GTD)
Forum:
  name: Forum
  description: Forums de discussion, fils de discussion communautaires et plateformes de questions-réponses
Habit Tracker:
  name: Suivi des habitudes
  description: Mettez en place des routines, suivez vos objectifs quotidiens et surveillez vos séries de jours consécutifs
Music Practice Tool:
  name: Outil de pratique musicale
  description: Accordeurs, métronomes, outils pour les accords et aides à la pratique des instruments
Location Tracker & Sharer:
  name: Suivi & partage de localisation
  description: Partager et suivre sa position GPS en temps réel avec d'autres personnes
AI Chat:
  name: Chat IA
  description: Assistants IA, chatbots, et interfaces pour les grands modèles de langage (LLM)
App Manager:
  name: Gestionnaire d'applications
  description: Gérer, organiser et contrôler les applications installées, les interactions (intent), les autorisations
Religion:
  name: Religion
  description: Applications proposant les horaires de prière, les textes sacrés, des méditations et des exercices spirituels
Clock:
  name: Horloge
  description: Alarmes, chronomètres, et utilitaires d'horloge mondiale
Firewall:
  name: Pare-feu
  description: Bloquer le trafic réseau indésirable et contrôler l'accès à internet des applications
Inventory:
  name: Inventaire
  description: Suivre, répertorier et gérer les articles physiques et les stocks
Network Analyzer:
  name: Analyseur de réseau
  description: Diagnostiquer le Wi-Fi, analyser les réseaux et surveiller les performances de connexion
Contact:
  name: Contact
  description: Applications de carnet d'adresses, répertoire et gestion des contacts
Battery:
  name: Batterie
  description: Surveiller et optimiser la durée de vie de la batterie, son utilisation et la charge
Flashlight:
  name: Lampe de poche
  description: Applications de lampe torche et de flash LED
Radio:
  name: Radio
  description: Écoutez en direct des stations de radio FM/AM et des émissions de radio sur Internet
Remote Controller:
  name: Télécommande
  description: Télécommandes IR et domotiques pour téléviseurs, climatiseurs et autres appareils
Remote Access:
  name: Accès à distance
  description: Contrôlez à distance les ordinateurs de bureau, les serveurs et les appareils via RDP, VNC ou SSH
Diet:
  name: Régime alimentaire
  description: Nutrition, calories, gestion alimentaire et suivi
Health Manager:
  name: Responsable santé
  description: Gérer le poids, la fréquence cardiaque, la tension artérielle, le cycle menstruel et d'autres indicateurs de santé
Schedule:
  name: Calendrier
  description: Programme de la conférence et de l'événement
Text to Speech:
  name: Synthèse vocale
  description: Outils de synthèse vocale
Time Tracker:
  name: Compteur de temps
  description: Suivre le temps consacré aux différentes activités et le temps passé devant un écran
Action Game:
  name: Jeu d'action
  description: Jeux d'action, de sport, de course et de plateforme
Board Game:
  name: Jeu de société
  description: Jeux de société, échecs, go, morpion
Card Game:
  name: Jeu de cartes
  description: Jeu de cartes, solitaire
Casual Game:
  name: Jeu occasionnel
  description: Jeu simple et décontracté
Dice:
  name: Dés
  description: Sélecteur aléatoire
Educational Game:
  name: Jeu éducatif
  description: Apprendre en jouant, quiz
Emulator:
  name: Émulateur
  description: Émulateur exécutant des jeux et des programmes
Game Helper:
  name: Aide au jeu
  description: Aide de jeu, assistant, compagnon, tableau d'affichage, chronomètre
Party Game:
  name: Jeu de société
  description: Jeu multijoueur, jeu festif
Platformer Game:
  name: Jeu de plateforme
  description: Jeu de plateforme à défilement horizontal
Puzzle Game:
  name: Jeu de réflexion
  description: Puzzle, sudoku, jeu de mémoire
Role-Playing Game:
  name: Jeu de rôle
  description: Jeu de rôle, rogue-like
Shooter Game:
  name: Jeu de tir
  description: Cible de tir
Strategy Game:
  name: Jeu de stratégie
  description: Stratégie, simulation
Sport Game:
  name: Jeu de sport
  description: Jeux de sport
Visual Novel:
  name: Roman visuel
  description: Roman visuel, jeu de rencontres, jeu narratif
Word Game:
  name: Jeu de lettres
  description: Jeu de mots, mots croisés, devinettes
Meditation:
  name: Méditation
  description: Méditation, bien-être mental, respiration
Timer:
  name: Minuteur
  description: Minuteur d'intervalles, chronomètre, compte à rebours
Download:
  name: Téléchargement
  description: Logiciel de téléchargement, gestionnaire de téléchargement et client torrent
File Manager:
  name: Gestionnaire de fichiers
  description: Gestionnaire de fichiers et explorateur
Camera:
  name: Appareil photo
  description: Caméra, visionneuse de caméras IP et enregistreur vidéo
Market & Price:
  name: Marché & Prix
  description: Prix, taux de change, stock
Recorder:
  name: Enregistreur
  description: Enregistrement audio, d'écran et d'appels
Lyrics:
  name: Paroles
  description: Consulter et rechercher des paroles
